### ISSUE TITLE
ModuleNotFoundError: No module named 'start'

### ISSUE THREAD

**Issue by chao-peng** [chao-peng/droidbot#1]
I have success install droidbot use: pip3 install -e . in WIN10 as:
successfully built droidbot
WARNING: Ignoring invalid distribution -ip (d:\programfiles\python39\lib\site-packages)
Installing collected packages: droidbot
Successfully installed droidbot-1.0.2b4

but run " droidbot -h" failed:
E:\AITestTT\droidbot>droidbot -h
Traceback (most recent call last):
File "D:\ProgramFiles\Python39\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "D:\ProgramFiles\Python39\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "D:\ProgramFiles\Python39\Scripts\droidbot.exe_main.py", line 4, in
ModuleNotFoundError: No module named 'start'

**Comment by chao-peng** [comment]
@mentatbot
